services:
  - type: web
    name: crud-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    branch: main

  - type: web
    name: crud-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    rootDir: client
    branch: main


